function msh = getMeshFromTriangleFile(filename, scale, shift)
%getMeshFromTriangleFile(filename, scale, shift) provides MATLAB struct MESH obtained from
% files generated by the Triangle software (Shewchuk)
%
% mesh = getMeshFromTriangleFile(filename, scale, shift)
%
% (C) 2020 Ralph-Uwe Börner
%

if nargin < 3
    shift = 0;
end

if nargin < 2
    scale = 1;
end

[msh.node, msh.tri2node, msh.tri2subdomain, msh.marker] = mesh.getTablesFromTriangle(filename);
msh.node = msh.node * scale;
msh.node(1, :) = shift + msh.node(1, :);

